apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-production
spec:
  secretName: certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: chicstyler.store
  dnsNames:
    - chicstyler.store
