name: manifests-deploy
on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      - run: doctl kubernates cluster kubeconfig save chicstyler
      - run: kubectl apply -f infra/k8
